setw -g mode-key vi

# Iterate from 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Reload config file
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# don't rename windows automatically
set-option -g allow-rename off

# Enter copy mode with PageUp
#bind-key -n PageUp copy-mode -u
#setw -g mode-keys vi

## COLORSCHEME: gruvbox dark
set -g status on

# default statusbar colors
set -g status-style bg=colour237,fg=colour223

# default window title colors
setw -g window-status-style bg=colour214,fg=colour237
setw -g window-status-activity-style bg=colour237,fg=colour248

# active window title colors
setw -g window-status-current-style bg=default,fg=colour237

# pane border
set -g pane-active-border-style fg=colour250,bg=colour237

# message infos
set -g message-style bg=colour239,fg=colour223

# writting commands inactive
set -g message-command-style bg=colour239,fg=colour223

# pane number display
set -g display-panes-active-colour colour250 #fg2
set -g display-panes-colour colour237 #bg1

# clock
setw -g clock-mode-colour colour109 #blue

# bell
setw -g window-status-bell-style fg=colour235,bg=colour167 #bg, red

## Theme settings mixed with colors (unfortunately, but there is no cleaner way)
set -g status-style "none" # bg=colour237 #bg1,fg=colour223,"none"
set -g status-justify "left"
set -g status-left-style "none"
set -g status-left-length "80"
set -g status-right-style "none"
set -g status-right-length "80"
setw -g window-status-activity-style "none" # bg=colour237,fg=colour248,"none"
setw -g window-status-style "none" # bg=colour214,fg=colour237,"none"
setw -g window-status-separator ""

set -g status-left "#[fg=colour248, bg=colour241] #S #[fg=colour241, bg=colour237, nobold, noitalics, nounderscore] > "
set -g status-right "#[fg=colour239, bg=colour237, nobold, nounderscore, noitalics]#[fg=colour246,bg=colour239] %Y-%m-%d | %H:%M #[fg=colour248, bg=colour239, nobold, noitalics, nounderscore]#[fg=colour237, bg=colour248] #h "

set -g window-status-format " #I:#W "
set -g window-status-current-format "#[fg=magenta,bold] #I:#W "
